version: '3'
services:
  catalog1:
    build:
      context: .
      dockerfile: src/main/java/catalog/Dockerfile
    image: catalog1-service
    ports:
      - "4567:4567"

  catalog2:
    build:
      context: .
      dockerfile: src/main/java/catalog/Dockerfile2
    image: catalog2-service
    ports:
      - "4570:4570"

  order1:
    build:
      context: .
      dockerfile: src/main/java/order/Dockerfile
    image: order1-service
    ports:
      - "4568:4568"

  order2:
    build:
      context: .
      dockerfile: src/main/java/order/Dockerfile2
    image: order2-service
    ports:
      - "4571:4571"

  frontend:
    build:
      context: .
      dockerfile: src/main/java/frontend/Dockerfile
    image: frontend-service
    ports:
      - "4569:4569"
